// tool/check_coverage.dart
//
// Parses coverage/lcov.info generated by `flutter test --coverage`:
//  - Prints per-file coverage with specific missed line numbers.
//  - Generates coverage/index.html with annotated source for each file.
//  - Prints total percentage at the end.
//  - Exits 1 if coverage < 100%.
//
// Usage (from app/):
//   dart tool/check_coverage.dart

import 'dart:io';

// ───────────────────────────────────────────────────────────── data classes ─

class FileCoverage {
  final String path;
  final Map<int, int> lines; // line → hit count

  FileCoverage(this.path, this.lines);

  int get linesFound => lines.length;
  int get linesHit => lines.values.where((h) => h > 0).length;
  List<int> get missedLines =>
      lines.entries.where((e) => e.value == 0).map((e) => e.key).toList()
        ..sort();
  bool get isFullyCovered => linesHit == linesFound;
}

// ─────────────────────────────────────────────────────────────────── parser ─

List<FileCoverage> parseLcov(File lcovFile) {
  final result = <FileCoverage>[];
  String? currentPath;
  final currentLines = <int, int>{};

  for (final line in lcovFile.readAsLinesSync()) {
    if (line.startsWith('SF:')) {
      currentPath = line.substring(3).trim();
      currentLines.clear();
    } else if (line.startsWith('DA:')) {
      final parts = line.substring(3).split(',');
      if (parts.length >= 2) {
        final lineNo = int.tryParse(parts[0]);
        final hits = int.tryParse(parts[1]);
        if (lineNo != null && hits != null) {
          currentLines[lineNo] = hits;
        }
      }
    } else if (line == 'end_of_record' && currentPath != null) {
      result.add(FileCoverage(currentPath, Map.of(currentLines)));
      currentPath = null;
      currentLines.clear();
    }
  }
  return result;
}

// ──────────────────────────────────────────────────────────── HTML helpers ─

String _pct(int hit, int found) =>
    found == 0 ? '100.0' : (hit / found * 100).toStringAsFixed(1);

String _pctColor(int hit, int found) {
  if (found == 0 || hit == found) return '#2e7d32'; // green
  final p = hit / found * 100;
  if (p >= 80) return '#f57c00'; // orange
  return '#c62828'; // red
}

String _escapeHtml(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

String buildHtml(List<FileCoverage> files) {
  final totalFound = files.fold(0, (s, f) => s + f.linesFound);
  final totalHit = files.fold(0, (s, f) => s + f.linesHit);
  final totalPct = _pct(totalHit, totalFound);
  final totalColor = _pctColor(totalHit, totalFound);

  final sb = StringBuffer();
  sb.writeln('''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Mapa Money — Coverage Report</title>
<style>
  body { font-family: system-ui, sans-serif; margin: 0; padding: 24px; background: #fafafa; color: #212121; }
  h1 { font-size: 1.4rem; margin-bottom: 4px; }
  .summary { font-size: 1.8rem; font-weight: 700; color: $totalColor; margin-bottom: 24px; }
  table { border-collapse: collapse; width: 100%; max-width: 860px; font-size: .9rem; }
  th { text-align: left; padding: 6px 12px; background: #263238; color: #fff; }
  td { padding: 5px 12px; border-bottom: 1px solid #e0e0e0; }
  tr:hover td { background: #f5f5f5; }
  .pct { font-weight: 600; }
  .bar-bg { background: #e0e0e0; border-radius: 4px; height: 8px; width: 120px; }
  .bar-fill { border-radius: 4px; height: 8px; }
  a { color: #1565c0; text-decoration: none; }
  a:hover { text-decoration: underline; }
  .file-block { margin-top: 32px; max-width: 900px; }
  .file-block h2 { font-size: 1rem; background: #263238; color: #fff; padding: 6px 12px; border-radius: 4px 4px 0 0; margin: 0; word-break: break-all; }
  .source { font-family: 'Cascadia Code', Consolas, monospace; font-size: .82rem; white-space: pre; overflow-x: auto; border: 1px solid #ccc; border-top: none; }
  .line { display: flex; }
  .ln { min-width: 44px; text-align: right; padding: 0 8px; color: #9e9e9e; background: #f5f5f5; border-right: 1px solid #e0e0e0; user-select: none; }
  .hits { min-width: 44px; text-align: right; padding: 0 8px; border-right: 1px solid #e0e0e0; font-size: .75rem; }
  .code { padding: 0 12px; flex: 1; }
  .hit   { background: #e8f5e9; }
  .miss  { background: #ffebee; }
  .instr { background: #fafafa; color: #9e9e9e; }
</style>
</head>
<body>
<h1>Mapa Money — Coverage Report</h1>
<div class="summary">$totalPct% ($totalHit / $totalFound lines)</div>
<table>
<tr><th>File</th><th>Lines</th><th>Hit</th><th>Coverage</th><th></th></tr>
''');

  for (final f in files..sort((a, b) => a.path.compareTo(b.path))) {
    final pct = _pct(f.linesHit, f.linesFound);
    final color = _pctColor(f.linesHit, f.linesFound);
    final fillWidth = f.linesFound == 0
        ? 120
        : (f.linesHit / f.linesFound * 120).round();
    final anchor = f.path.replaceAll(r'\', '_').replaceAll('/', '_');
    sb.writeln('''<tr>
<td><a href="#$anchor">${_escapeHtml(f.path)}</a></td>
<td>${f.linesFound}</td>
<td>${f.linesHit}</td>
<td class="pct" style="color:$color">$pct%</td>
<td><div class="bar-bg"><div class="bar-fill" style="width:${fillWidth}px;background:$color"></div></div></td>
</tr>''');
  }
  sb.writeln('</table>');

  // Per-file annotated source blocks
  for (final f in files) {
    final anchor = f.path.replaceAll(r'\', '_').replaceAll('/', '_');
    sb.writeln('<div class="file-block" id="$anchor">');
    sb.writeln('<h2>${_escapeHtml(f.path)}</h2>');
    sb.writeln('<div class="source">');

    final srcFile = File(f.path);
    if (srcFile.existsSync()) {
      final srcLines = srcFile.readAsLinesSync();
      for (var i = 0; i < srcLines.length; i++) {
        final lineNo = i + 1;
        final hits = f.lines[lineNo];
        String cls, hitsStr;
        if (hits == null) {
          cls = 'instr';
          hitsStr = '';
        } else if (hits > 0) {
          cls = 'hit';
          hitsStr = '$hits';
        } else {
          cls = 'miss';
          hitsStr = '0';
        }
        sb.writeln(
          '<div class="line $cls">'
          '<span class="ln">$lineNo</span>'
          '<span class="hits">$hitsStr</span>'
          '<span class="code">${_escapeHtml(srcLines[i])}</span>'
          '</div>',
        );
      }
    } else {
      sb.writeln('<div class="line instr"><span class="code">(source not found)</span></div>');
    }

    sb.writeln('</div></div>');
  }

  sb.writeln('</body></html>');
  return sb.toString();
}

// ──────────────────────────────────────────────────────────────────── main ─

void main() {
  final lcovFile = File('coverage/lcov.info');
  if (!lcovFile.existsSync()) {
    stderr.writeln(
      'coverage/lcov.info not found.\nRun: flutter test --coverage',
    );
    exit(1);
  }

  final files = parseLcov(lcovFile);
  if (files.isEmpty) {
    stderr.writeln('No coverage data found in coverage/lcov.info.');
    exit(1);
  }

  final totalFound = files.fold(0, (s, f) => s + f.linesFound);
  final totalHit = files.fold(0, (s, f) => s + f.linesHit);

  // ── terminal output ───────────────────────────────────────────────────────
  stdout.writeln('');
  stdout.writeln('Coverage report:');
  stdout.writeln('─' * 62);

  for (final f in files..sort((a, b) => a.path.compareTo(b.path))) {
    final pct = _pct(f.linesHit, f.linesFound);
    final label = '  ${f.path}'.padRight(46);
    stdout.writeln('$label ${f.linesHit.toString().padLeft(3)}/${f.linesFound}  $pct%');
    if (f.missedLines.isNotEmpty) {
      stdout.writeln('    Missed lines: ${f.missedLines.join(', ')}');
    }
  }

  stdout.writeln('─' * 62);
  final totalPct = _pct(totalHit, totalFound);
  final totalHitStr = totalHit.toString().padLeft(3);
  stdout.writeln('  ${'TOTAL'.padRight(44)} $totalHitStr/$totalFound  $totalPct%');
  stdout.writeln('');

  // ── HTML report ───────────────────────────────────────────────────────────
  final htmlDir = Directory('coverage');
  if (!htmlDir.existsSync()) htmlDir.createSync();
  final htmlFile = File('coverage/index.html');
  htmlFile.writeAsStringSync(buildHtml(files));
  stdout.writeln('HTML report: coverage/index.html');
  stdout.writeln('');

  // ── pass / fail ───────────────────────────────────────────────────────────
  if (totalHit < totalFound) {
    stderr.writeln('FAIL: Coverage is $totalPct% — 100% required.');
    exit(1);
  }
  stdout.writeln('PASS: 100% line coverage.');
}

